services:
  - type: web
    name: Xstro
    runtime: docker
    repo: https://github.com/XJAY-GAMING/XJAY-XSTRO-MD
    plan: free
    envVars:
      - key: SESSION-ID
        sync: true
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
version: '1'
